### PR TITLE
Better feature build + Claude 3.5 support

### PR DESCRIPTION
**Pull request by amirrr**
Will add a better feature builder (adjustable features) and the ability to use function call on Anthropic claude 3.5

Sadly the Claude API is garbage and just spits out JSON file when it should give a proper object. Very unreliable.

### CODE REVIEW

**Review by markwhiting — CHANGES_REQUESTED** [review]
Cool, but I feel like we should fix the hard-coded features before embarking on this. We're pushing our technical debt down the road. 

Also, should we work out the JSON aspect before pushing it to production? Can you say more about how that does or doesn't work and what seems to work as a fix? (one simple fix would be to give the function and the response to GPT4o and ask it to clean it up and format it as the function requests)

**Comment by amirrr** [comment]
> Cool, but I feel like we should fix the hard-coded features before embarking on this. We're pushing our technical debt down the road.
> 
> Also, should we work out the JSON aspect before pushing it to production? Can you say more about how that does or doesn't work and what seems to work as a fix? (one simple fix would be to give the function and the response to GPT4o and ask it to clean it up and format it as the function requests)

Hard coded features on the server side are taken care of just the client side remains which I will update.
The ability to select the model is for now not displayed but all the puzzle pieces are there for a call using Claude3.5 model.
Regarding the output I tried asking GPT to fix the output and even asked claude itself but it seems to make the same mistake as claude did with the same data, here is a sample:

it seems to be putting everything inside a quote under "experiment" tag, string manipulation also broke the json format. There might be a way to fix this, but claude endpoint on function calls seem unreliable.

```json
{
  "experiments": "[\n  {\n    \"name\": \"Artificial Music Market Experiment\",\n    \"description\": \"An artificial 'music market' was created in which 14,341 participants downloaded previously unknown songs either with or without knowledge of previous participants' choices. The experiment investigated how social influence affects inequality and unpredictability of success in cultural markets.\",\n    \"participant_source\": \"teen-interest World Wide Web site\",\n    \"participant_source_category\": \"online panel\",\n    \"units_randomized\": \"individuals\",\n    \"units_analyzed\": \"individuals\",\n    \"sample_size_randomized\": 14341,\n    \"sample_size_analyzed\": 14341,\n    \"sample_size_notes\": \"NA\",\n    \"adults\": \"both\",\n    \"age_mean\": <UNKNOWN>,\n    \"age_sd\": <UNKNOWN>,\n    \"female_perc\": <UNKNOWN>,\n    \"male_perc\": <UNKNOWN>,\n    \"gender_other\": <UNKNOWN>,\n    \"language\": \"English\",\n    \"language_secondary\": \"NA\",\n    \"compensation\": <UNKNOWN>,\n    \"demographics_conditions\": \"No\",\n    \"population_other\": \"Participants were recruited mostly from a teen-interest World Wide Web site\",\n    \"conditions\": [\n      {\n        \"name\": \"Independent\",\n        \"description\": \"Participants made decisions about which songs to listen to, given only the names of the bands and their songs, without any information about previous choices of others.\",\n        \"type\": \"plain vanilla control\",\n        \"message\": \"No\",\n        \"behaviors\": [\n          {\n            \"name\": \"Song downloads\",\n            \"description\": \"Number of times each song was downloaded\",\n            \"priority\": \"primary\",\n            \"focal\": \"focal\"\n          },\n          {\n            \"name\": \"Song ratings\",\n            \"description\": \"Ratings assigned to songs by participants\",\n            \"priority\": \"secondary\",\n            \"focal\": \"not focal\"\n          }\n        ]\n      },\n      {\n        \"name\": \"Social influence\",\n        \"description\": \"Participants could see how many times each song had been downloaded by previous participants, in addition to the names of the bands and songs.\",\n        \"type\": \"treatment\",\n        \"message\": \"No\",\n        \"behaviors\": [\n          {\n            \"name\": \"Song downloads\",\n            \"description\": \"Number of times each song was downloaded\",\n            \"priority\": \"primary\",\n            \"focal\": \"focal\"\n          },\n          {\n            \"name\": \"Song ratings\",\n            \"description\": \"Ratings assigned to songs by participants\",\n            \"priority\": \"secondary\",\n            \"focal\": \"not focal\"\n          }\n        ]\n      }\n    ]\n  }\n]"
}

```

**Review by markwhiting — APPROVED** [review]
In that case, good to go!

**Comment by amirrr** [comment]
> In that case, good to go!

Then I'll update front-end with the code from observable and then merge.

Here is claude response to common-sense paper:
```json
{
    "experiments": "[\n  {\n    \"name\": \"Common Sense Evaluation\",\n    \"description\": \"This experiment evaluated the commonsensicality of various claims by having participants rate their agreement with claims and predict others' agreement. It also assessed participants' social perceptiveness and cognitive reflection abilities.\",\n    \"participant_source\": \"Amazon Mechanical Turk\",\n    \"participant_source_category\": \"online panel\",\n    \"units_randomized\": \"individuals\",\n    \"units_analyzed\": \"individuals and claims\",\n    \"sample_size_randomized\": 2046,\n    \"sample_size_analyzed\": 2046,\n    \"sample_size_notes\": \"2,046 participants rated 4,407 claims, with each participant rating 50 randomly selected claims\",\n    \"adults\": \"adults\",\n    \"age_mean\": <UNKNOWN>,\n    \"age_sd\": <UNKNOWN>,\n    \"female_perc\": <UNKNOWN>,\n    \"male_perc\": <UNKNOWN>,\n    \"gender_other\": <UNKNOWN>,\n    \"language\": \"English\",\n    \"language_secondary\": \"NA\",\n    \"compensation\": \"Workers received pay at a rate of $15/h, based on the median time for completion across all participants\",\n    \"demographics_conditions\": \"No\",\n    \"population_other\": \"Participants completed the Reading the Mind in the Eyes test and Cognitive Reflection Test\",\n    \"conditions\": [\n      {\n        \"name\": \"Claim Rating\",\n        \"description\": \"Participants rated their agreement with claims and predicted others' agreement\",\n        \"type\": \"treatment\",\n        \"message\": \"No\",\n        \"behaviors\": [\n          {\n            \"name\": \"Claim Agreement\",\n            \"description\": \"Whether participant agrees with claim\",\n            \"priority\": \"primary\",\n            \"focal\": \"focal\"\n          },\n          {\n            \"name\": \"Predicted Agreement\",\n            \"description\": \"Participant's prediction of others' agreement\",\n            \"priority\": \"primary\",\n            \"focal\": \"not focal\"\n          }\n        ]\n      }\n    ]\n  }\n]"
}
```

**Pull request merged**
